name: Build release
on:
  push:
    tags:
    - '*'

jobs:
  build_gesso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - run: |
          npm i -g npm@9
          npm ci
          npm run build
      - run: |
          rm -rf node_modules
      - name: Set version number
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'slac.info.yml'
          propertyPath: 'version'
          value: ${{ github.ref_name }}
          commitChange: false
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'slac.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig source/*'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'slac.zip'
          replacesArtifacts: true
          allowUpdates: true
